import type { Metadata } from "next/types";
import "@/styles/globals.css"
import { Providers } from "@/provider"
// import Image from "next/image"

import localFont from "next/font/local"
const lineSeedSansTH = localFont({
  src: [
    { path: "../../public/fonts/LINESeedSansTH_W_Th.woff2", weight: "300", style: "normal" },
    { path: "../../public/fonts/LINESeedSansTH_W_Rg.woff2", weight: "400", style: "normal" },
    { path: "../../public/fonts/LINESeedSansTH_W_Bd.woff2", weight: "500", style: "normal" },
    { path: "../../public/fonts/LINESeedSansTH_W_Bd.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-line-seed",
  display: "swap",
})


export const metadata: Metadata = {
  title:
    "PCSHS | โรงเรียนวิทยาศาสตร์จุฬาภรณราชวิทยาลัย",
  description: "Generated by PHA-NU-WAT",
  icons: {
    icon: "/favicon.ico",
    apple: "/icons/icon-192.png",
  },
  manifest: "/manifest.json",
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="th" className={lineSeedSansTH.variable} suppressHydrationWarning>
      <head>
        <meta name="theme-color" content="#0f172a" />
      </head>
      {/* <body className="font-lineSeed font-sans antialiased"> */}
      <body className="font-lineSeed antialiased">
        {/* <Image
          src="/img/black_ribbon_bottom_right.png"
          alt=""
          width={70}
          height={70}
          loading="eager"
          priority 
          className="black-ribbon stick-bottom stick-right"
        /> */}
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
